### ISSUE TITLE
Package Error when Installing/running

### ISSUE THREAD

**Issue by Luciaisacomputer** [gabrielmoreira/craftman#18]
When I run `craftman --port=8080 install` I get the following error:

**E: Package 'libpng12-dev' has no installation candidate**

If I change `libpng12-dev` to `libpng-dev` in `010_dependencies.sh` it seems to install correctly.  

It looks like the 12 version has been dropped https://askubuntu.com/questions/991706/e-package-libpng12-dev-has-no-installation-candidate

**Comment by ashbryant** [comment]
I too get this error
