### ISSUE TITLE
Remove unzip dependency or add it to the docs

### ISSUE THREAD

**Issue by yn5** [gabrielmoreira/craftman#5]
Running `craftman --port 8080 install` I get the following error: `line 389: unzip: command not found`. (Running Ubuntu 14.04.3)

**Comment by gabrielmoreira** [comment]
@yn5, Thank you for your suggestion. Sorry for the delay to respond, I was on vacation.

I need to change `https://craftcms.com/latest.zip?accept_license=yes` to `https://craftcms.com/latest.tar.gz?accept_license=yes` and change `unzip` to `tar -vzxf`.

Once I have a little time, I will make this change.

**Comment by yn5** [comment]
@gabrielmoreira Thanks for your response, would be great to have this fixed, I seem to have a hard time finding a decent Craft CMS Docker image.

**Comment by gabrielmoreira** [comment]
@yn5 Can you upgrade craftman to latest version and try again?
Just run `craftman --upgrade`

**Comment by yn5** [comment]
@gabrielmoreira Yes this seems to have fixed that particular problem, thanks!
