### ISSUE TITLE
Public folder name is changed

### ISSUE THREAD

**Issue by joshmedeski** [gabrielmoreira/craftman#6]
Hi Gabriel,

I noticed that Craftman uses a different folder name for the public directory.

Craft's convention is to name the public directory `public`, but Craftman creates a folder called `html`.

Why are they different? I would like to deploy my site and the difference in this folder name make is more difficult.

Thanks.

**Comment by gabrielmoreira** [comment]
@joshmedeski, First, sorry for the delay in responding. I was on vacation.

You're right. When I did, I think the main reason was to avoid reconfiguring Apache. The default public directory in apache is `/var/www/html`. So the craft is located in the `/var/www/craft`, while the public is located in the `/var/www/html`.

Change the directory name was not a problem in my case, however, I recognize that it is at least a strange decision.

I think I need help to think better of it. Use the `html` directory, facilitates installation and avoid reset / remove the default Apache configuration.

Can you explain the environment that you are making deploy, and how do you do it?

**Comment by joshmedeski** [comment]
We have things figured out @gabrielmoreira. I was just curious about why they are different.

We've got a good solution using our build tool 😄
