### ISSUE TITLE
Is this my, craftman, or debian's issue? 

### ISSUE THREAD

**Issue by bgrrtt** [gabrielmoreira/craftman#9]
```
Get:149 http://httpredir.debian.org/debian/ jessie/main vim amd64 2:7.4.488-7 [953 kB]
Fetched 64.0 MB in 2min 12s (482 kB/s)
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/d/djvulibre/libdjvulibre-dev_3.5.25.4-4+b1_amd64.deb  Error reading from server. Remote end closed connection [IP: 128.31.0.66 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

~/S/craftman-test >>> craftman --upgrade                                                                                                                        ⏎
Already up-to-date.
```

Not sure where to start. Thanks!

**Comment by Nilloc** [comment]
Had the same issue with new install, file seems to be available and manually downloadable...

Could be missing something else too, but `mysite_craft_1` and `mysite_mysql_1` containers start, but `mysite_mysql_data_1` isn't starting, and the site (while running) isn't connecting to the DB.

**Comment by nicbou** [comment]
Try running `docker-compose up --build --no-cache`. This is an issue with docker caching the repo update step.
